name: Semgrep via Shared Workflow
on:
  workflow_dispatch: 
  pull_request: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '15 20 * * *'
jobs:
  call-workflow:
    uses: headway/actions/.github/workflows/semgrep.yaml@a39164693e31e3c249bf7b669b1589ae044a4103
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}